# Generated by Django 4.2.7 on 2025-12-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('wa_id', models.CharField(help_text='WhatsApp ID of the sender', max_length=50)),
                ('from_number', models.CharField(help_text='Phone number of the sender', max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('location', 'Location'), ('contacts', 'Contacts'), ('sticker', 'Sticker')], max_length=20)),
                ('message_text', models.TextField(blank=True, help_text='Text content if message type is text', null=True)),
                ('audio_id', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_voice', models.BooleanField(default=False)),
                ('timestamp', models.CharField(max_length=50)),
                ('phone_number_id', models.CharField(help_text="Meta's phone number ID", max_length=100)),
                ('display_phone_number', models.CharField(help_text='Display phone number', max_length=50)),
                ('raw_payload', models.JSONField(default=dict, help_text='Complete webhook payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this message has been processed by chatbot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wa_id', '-created_at'], name='webhook_wha_wa_id_4f138a_idx'), models.Index(fields=['message_type'], name='webhook_wha_message_7a22aa_idx'), models.Index(fields=['processed'], name='webhook_wha_process_caa75d_idx')],
            },
        ),
    ]
