# Generated by Django 4.2.7 on 2025-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='contacts_data',
            field=models.JSONField(blank=True, help_text='Contact information in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='document_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='document_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='document_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_animated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sticker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sticker_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sticker_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='video_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='video_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
