# Generated by Django 4.2.7 on 2025-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_whatsappmessage_contacts_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(help_text='Unique call ID from WhatsApp', max_length=255)),
                ('from_number', models.CharField(help_text='Phone number of the caller', max_length=50)),
                ('to_number', models.CharField(help_text='Phone number being called', max_length=50)),
                ('wa_id', models.CharField(help_text='WhatsApp ID of the caller', max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.CharField(choices=[('connect', 'Connect'), ('terminate', 'Terminate')], help_text='Call event type: connect or terminate', max_length=20)),
                ('direction', models.CharField(choices=[('USER_INITIATED', 'User Initiated'), ('BUSINESS_INITIATED', 'Business Initiated')], help_text='Who initiated the call', max_length=30)),
                ('status', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('DECLINED', 'Declined'), ('FAILED', 'Failed'), ('BUSY', 'Busy'), ('NO_ANSWER', 'No Answer')], help_text='Call status (available on terminate)', max_length=20, null=True)),
                ('timestamp', models.CharField(help_text='Event timestamp', max_length=50)),
                ('start_time', models.CharField(blank=True, help_text='Call start time (available on completed calls)', max_length=50, null=True)),
                ('end_time', models.CharField(blank=True, help_text='Call end time (available on completed calls)', max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('session_sdp', models.TextField(blank=True, help_text='SDP offer/answer for WebRTC', null=True)),
                ('session_sdp_type', models.CharField(blank=True, help_text='SDP type: offer or answer', max_length=20, null=True)),
                ('phone_number_id', models.CharField(help_text="Meta's phone number ID", max_length=100)),
                ('display_phone_number', models.CharField(help_text='Display phone number', max_length=50)),
                ('raw_payload', models.JSONField(default=dict, help_text='Complete call webhook payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['call_id'], name='webhook_wha_call_id_edca20_idx'), models.Index(fields=['from_number', '-created_at'], name='webhook_wha_from_nu_12d82a_idx'), models.Index(fields=['event'], name='webhook_wha_event_e3d2aa_idx'), models.Index(fields=['status'], name='webhook_wha_status_b8b676_idx')],
            },
        ),
    ]
