# Generated by Django 4.2.7 on 2025-12-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_whatsappcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappcall',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='whatsappcall',
            name='end_time',
            field=models.CharField(blank=True, help_text='Call end time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcall',
            name='session_sdp',
            field=models.TextField(blank=True, help_text='SDP offer/answer for WebRTC call handling', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcall',
            name='start_time',
            field=models.CharField(blank=True, help_text='Call start time', max_length=50, null=True),
        ),
    ]
