# Generated by Django 4.2.7 on 2026-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_remove_whatsappcall_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID of the message this status refers to', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], help_text='Message status', max_length=20)),
                ('recipient_id', models.CharField(help_text='Phone number of the recipient', max_length=50)),
                ('conversation_id', models.CharField(blank=True, help_text='Conversation ID', max_length=255, null=True)),
                ('conversation_expiration_timestamp', models.CharField(blank=True, help_text='Conversation expiration timestamp', max_length=50, null=True)),
                ('conversation_origin_type', models.CharField(blank=True, help_text='Origin type (service/user)', max_length=50, null=True)),
                ('is_billable', models.BooleanField(default=False, help_text='Whether the message is billable')),
                ('pricing_model', models.CharField(blank=True, help_text='Pricing model (e.g., PMP)', max_length=50, null=True)),
                ('pricing_category', models.CharField(blank=True, help_text='Pricing category (e.g., service)', max_length=50, null=True)),
                ('pricing_type', models.CharField(blank=True, help_text='Pricing type (e.g., free_customer_service)', max_length=100, null=True)),
                ('timestamp', models.CharField(help_text='Status timestamp', max_length=50)),
                ('phone_number_id', models.CharField(help_text="Meta's phone number ID", max_length=100)),
                ('display_phone_number', models.CharField(help_text='Display phone number', max_length=50)),
                ('raw_payload', models.JSONField(default=dict, help_text='Complete status payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message_id', '-created_at'], name='webhook_wha_message_58ec47_idx'), models.Index(fields=['status'], name='webhook_wha_status_76de4e_idx'), models.Index(fields=['recipient_id', '-created_at'], name='webhook_wha_recipie_360cb1_idx')],
            },
        ),
    ]
