# Generated by Django 4.2.7 on 2026-01-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_whatsappmessagestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, help_text='WhatsApp message ID returned from API', max_length=255, null=True, unique=True)),
                ('to_number', models.CharField(help_text='Recipient phone number', max_length=50)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='text', max_length=20)),
                ('message_text', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', help_text='Current message status', max_length=20)),
                ('api_response', models.JSONField(blank=True, help_text='Response from WhatsApp API', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When message was successfully sent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_number', '-created_at'], name='webhook_wha_to_numb_32f61f_idx'), models.Index(fields=['status'], name='webhook_wha_status_efd465_idx'), models.Index(fields=['message_id'], name='webhook_wha_message_2431de_idx')],
            },
        ),
    ]
